name: å¤šæ¶æ„ Tftp æ„å»º | Multiarch Tftp Build

on:
  workflow_dispatch

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  tftpbuild:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”„ æ£€å‡ºä»£ç  | Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ é…ç½® Docker Buildx | Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” ç™»å½• Docker Hub | Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸš€ æ„å»ºå¹¶æ¨é€é•œåƒ | Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/netboot-tftp.dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tftp:latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/tftp
          readme-filepath: ./docker/tftp.md

      - name: âœ… å®Œæˆå¹¶è¾“å‡ºä¿¡æ¯ | Complete and Print Info
        run: |
          echo "Tftp é•œåƒå·²æ„å»ºå¹¶æ¨é€"
          echo "Tftp image has been built and pushe"